# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Don't edit manually! Use `build.bat version` command instead!
version: 0.5.0-build-0{build}

os: Visual Studio 2019

environment:
  BuildEnvironment: appveyor

nuget:
  project_feed: true
  disable_publish_on_pr: true

shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script: build.bat pack

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'

deploy:
  - provider: NuGet
    skip_symbols: true
    api_key: 
      secure: sE88DSEBBhC+hDgI1+JICzwWjwwmxSyNEWfUjED6ZAs6f9oDD85V0qpbGLWBn+gL
    on:
      appveyor_repo_tag: true
